### ISSUE TITLE
404 on refresh post

### ISSUE THREAD

**Issue by influx-agence** [nuxt-community/nuxtent-module#180]
**Describe the bug**
Hello,
That's my problem:
When I go to my blog, the list of articles is displayed well. Once I go to an article and refresh the page I find a 404 error.
Looking more ready the networks I realize that the .JSON normally called has two points after refreshment
(*Myurl.com/_nuxt/content/name..json*)
Someone will have an idea where it might come from?
Thx for your rep :+1: 

**To Reproduce**
1. Go to 'https://influx-agence.netlify.com/blog/'
2. Click on 'My second blog'
3. Look the web console network ( 2018.premier-posts.json )
4. Refresh page
5. The page is 404
6. Look web console network ( 2018.premier-posts**..**json )

**Screenshots**
3. Before refresh
![image](https://user-images.githubusercontent.com/43016695/45427881-4c8afd80-b6a0-11e8-881d-337f3e3a15f7.png)
6. After refresh
![image](https://user-images.githubusercontent.com/43016695/45428040-aab7e080-b6a0-11e8-81b3-4f6cad712be4.png)

**Applicable Versions:**
 - Nuxt : Last
 - Netlify CMS : Last
 - Node.JS : 8.12.0

**CMS configuration**
```
backend:
  name: github
  repo: influx-agence/Nuxtlify
  branch: master
media_folder: "static/uploads"
display_url: https://influx-agence.netlify.com
collections: # A list of collections the CMS should be able to edit
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog" # Used in the UI, ie.: "New Post"
    folder: "content/posts"
    extension: "json"
    format: "json"
    create: true
    slug: "{{year}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "DD-MM-YYYY"}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
- {label: "SEO Description", name: "description", widget: "text"}
```

**Additional context**
https://github.com/influx-agence/Nuxtlify

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7729">#c7729</a>)</em></sub></div>
